FROM python:3.10-buster

WORKDIR /subscriber

# Manage dependencies
COPY ./requirements.txt /subscriber/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /subscriber/requirements.txt
# Make RUN commands use the new environment:
#SHELL ["conda", "run", "-n", "schedule", "/bin/bash", "-c"]

COPY ./subscriber/ /subscriber/
ENV PYTHONPATH "${PYTHONPATH}:/scheduler"