name: 'Setup Python with uv'
description: 'Set up Python environment with uv and install dependencies'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Restore uv cache
      uses: actions/cache@v4
      with:
        path: /tmp/.uv-cache
        key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: uv sync --cache-dir /tmp/.uv-cache --all-groups
